### ISSUE TITLE
Request for explanation of the code-base

### ISSUE THREAD

**Issue by strikersps** [H3inAK/fbhacker#1]
@H3inAK Can you provide a more descriptive `readme.md` file explaining how the tool is able to crack the victim's password using the brute-force attack method.

There are some instructions in the code, which I quite don't understand:  

1. Significance of the following instructions:  
`cookie = {'fr':'0ZvhC3YwYm63ZZat1..Ba0Ipu.Io.AAA.0.0.Ba0Ipu.AWUPqDLy'}`  
`data = BeautifulSoup(data.text,'html.parser').form`

2.  What the following function does:  
``` python3
def function(email,passw,i):
    global payload,cookie
    if i%10 == 1:
        payload,cookie = create_form()
        payload['email'] = email
    payload['pass'] = passw
    print(payload)
    print(cookie)
    print('lsd : ',payload['lsd'])
    print(cookie)
    r = requests.post(post_url,data=payload,cookies=cookie,headers=headers)
    if 'Find Friends' in r.text:
        open('d.html','w').write(r.text)
        return True
    return False
```
I was trying to understand the above function, I am having trouble in understanding the logic of the above function defined in your code:  

1. Why are you are taking `modulo 10 of i-values`.  
2. What the meaning of the condition:  
```python3
if 'Find Friends' in r.text:
    open('d.html','w').write(r.text)
    return True
```
It would be better if you provide a descriptive `readme.md` file for your code-base.

**Comment by iamsonoob** [comment]
You better change your password. Because this script looks malicious. I did put the real password in the wordlists, but it does not work

I think this is a tactic of him
1) Let user put real pass + id (for testing)
2) Sending the credentials back to this guy
--> You got hack =))

**Comment by up2smoke** [comment]
Coward

**Comment by sr326201** [comment]
Speak more clearly, I do not understand, write better
