### ISSUE TITLE
Dont working in kali Linux !

### ISSUE THREAD

**Issue by up2smoke** [H3inAK/fbhacker#4]
I wrote 10 passwords in a pass.txt file in /home/kali/
On the 7 place, i wrote my real password... The tool dont regnotize it and tryed the next password.
Fail !

**Comment by sr326201** [comment]
Hi, where are you from

**Comment by sr326201** [comment]
What?


در تاریخ یکشنبه ۱۷ ژانویهٔ ۲۰۲۱،‏ ۱۷:۴۴ up2smoke <notifications@github.com>
نوشت:
