### ISSUE TITLE
don't be a coward!

### ISSUE THREAD

**Issue by up2smoke** [H3inAK/fbhacker#5]
do not delete the error messages, better deal with the problems!  or are you so pathetic?  just close the treat without going into it?  then you don't need to publish your shit and brag about it!

**Comment by thantzinoo-dev** [comment]
I need to update it.
This repo was about two years ago.
Facebook have been updating their security.
It even refuse valid credentials if you try more than 3 times.
I created this tool just for fun.
I will replace this tool with new one.
New one will have more features.
I will make it to be available for android, ios and even windows and mac os.
Not just brute forcing.
It can be spy all activities from victims.

**Comment by up2smoke** [comment]
nice to hear that
